ARG version
FROM almalinux:${version:-8}
LABEL COURSE="Docker" \
      DURATION="30days" \
      TIME="Morning"      
RUN echo "Course is ${COURSE}, version is ${version}"
CMD ["sleep", "200"]

      